POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "id": "",
    "title": "thtree thing",
    "author": "KX",
    "url": "itravel.com",
    "likes": 102,
    "userId": "66f4c65bb99d0a1bb61523a5"

}

