DELETE  http://localhost:3003/api/blogs/66f8e7aa25e4b8efdea071fc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNhc3VrZSIsImlkIjoiNjZmOGU3MzEyNWU0YjhlZmRlYTA3MWY2IiwiaWF0IjoxNzI3NTg4MTgxfQ.dsehHdS8d1Vpu3kd5a1xwPfwMz73uNKu5NYaT5kGnXo

{
    "id": "66f8e7aa25e4b8efdea071fc",
    "title": "Sasukes blog, see if naruto can",
    "author": "KX",
    "url": "itravel.com",
    "likes": 102,
    "userId": "66f4c65bb99d0a1bb61523a5"

}